### ISSUE TITLE
Question: Mexico Keys in Place dic and print_stats_states function

### ISSUE THREAD

**Issue by cespinosa** [Morisset/plot_COVID_Mex#1]
There are two Mexico keys in place_dic dictionary for whole country, but there is a 'ESTADOS UNIDOS MEXICANOS' key. In print_states_states function, what key use to print the info for the whole country?

**Comment by Morisset** [comment]
The first two keywords are pointing to the same data: the whole country. This can be seen from the population. I did not succeed yet to also print out the stats for the Estado de Mexico. Will try in the next days.

**Comment by Morisset** [comment]
Other states are also missing. Still some work has to be done...

**Comment by Morisset** [comment]
Solved using "'Total de la entidad México".
